services:

  backend:
    build:
      context: ./BackEnd
    container_name: backend
    command: /bin/bash -c "python manage.py makemigrations App && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./BackEnd:/app
    ports:
      - "8090:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
        # Stripe specific keys
        - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "3501:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8090


  stripe:
    build: ./stripe  # Path to your Stripe Dockerfile
    container_name: stripe
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEVICE_NAME=docker-webhook
      - STRIPE_WEBHOOK_SIGNING_SECRET=${STRIPE_WEBHOOK_SECRET}
    depends_on:
      - backend  # Ensure the web service is up before starting Stripe
    restart: unless-stopped
  

  db:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
