services:
  backend:
    build:
      context: ./BackEnd
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./BackEnd:/app
    ports:
      - "8090:8000"
    env_file:
      - .env
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    ports:
      - "3501:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8090



  db:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
