# Generated by Django 5.1.3 on 2024-12-02 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 20, 54, 32, 944182, tzinfo=datetime.timezone.utc)),
        ),
    ]
